# Generated by Django 4.1.7 on 2023-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("teacher", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=63)),
                ("age_of_pupils", models.IntegerField()),
                ("price", models.IntegerField()),
                ("school_subject", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("courses", models.ManyToManyField(to="catalog.course")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
