# Generated by Django 4.1.7 on 2023-03-31 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_coast",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="age_of_pupils",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(7),
                    django.core.validators.MaxValueValidator(18),
                ]
            ),
        ),
    ]
