# Generated by Django 4.1.7 on 2023-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_course_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_coast",
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
