# Generated by Django 4.1.7 on 2023-04-05 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_order_total_coast"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_coast",
            new_name="total_cost",
        ),
    ]
