# Generated by Django 4.1.7 on 2023-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_rename_total_coast_order_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
